name: screenutil_module
description: "this module is a part of the juneflow project, it provides a screenutil module for flutter project."
#publish_to: 'none'
repository: https://github.com/juneflow-songdo/screenutil_module

version: 1.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router:
  june_flow_util:
  flutter_screenutil: #@add

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true