name: screenutil_module
description: "JuneFlow Module"
#publish_to: 'none'
#repository: https://github.com/melodysdreamj/juneflow

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.2.0
  june_flow_util:
  flutter_screenutil: ^5.5.3+2 #@add

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true